export const QUESTION_VOICES = [
  ["campbell", "Campbell"],
  ["franz", "von Franz"],
  ["hillman", "Hillman"],
  ["coelho", "Coelho"],
] as const;

export type QuestionVoice = (typeof QUESTION_VOICES)[number][0];

export type MythQuestions = Record<QuestionVoice, string>;

export const MYTH_QUESTIONS: Record<string, MythQuestions> = {
  persephone: {
    campbell: "Where is return possible, and where would return be a lie?",
    franz: "What season of yourself are you refusing to name as a season?",
    hillman: "What did you eat in the dark that is trying to feed you now, not to be spit out?",
    coelho: "If the underworld left one omen in your ordinary day, what would it be?",
  },
  psyche: {
    campbell: "What lamp are you refusing to lift, and what would you owe yourself if you did?",
    franz: "Which voice from the old life is still calling the dark a monster?",
    hillman: "Which impossible task is soul-making, not a problem to be solved?",
    coelho: "Can you love with the light on, and still keep the oil on the spoon?",
  },
  odysseus: {
    campbell: "What is the home you keep postponing, and what in you prefers the sea?",
    franz: "Where are you still nobody because a name would make you accountable?",
    hillman: "What longing is intelligent here, and not a delay to be cured?",
    coelho: "Who has been weaving in your absence, and have you honored that labor?",
  },
  ariadne: {
    campbell: "Where in your life are you the map and never the traveler?",
    franz: "What did you hand over that you now need back as your own thread?",
    hillman: "If no one needed you to be useful, what image would you become?",
    coelho: "What small thread is already in your hand, that you keep calling a maze?",
  },
  orpheus: {
    campbell: "Where is your glance stealing a future that needed a little more dark?",
    franz: "What song of yours still works even after the loss?",
    hillman: "Can you love something you cannot supervise, without turning it into a project?",
    coelho: "What omen did you treat as a guarantee, and look back too soon?",
  },
  prometheus: {
    campbell: "Which of your gifts is a theft from a smaller life you were told to live?",
    franz: "Where are you confusing a necessary sacrifice with a habit of being eaten?",
    hillman: "What fire in you wants to be tended, not proven?",
    coelho: "If the eagle came tomorrow, would you still call the ordinary work worth it?",
  },
  athena: {
    campbell: "What decision have you been trying to feel through that actually wants a strategy?",
    franz: "Which armor is still useful, and which is leftover from a war that ended?",
    hillman: "What fury in you needs a court, not an exile and not a cure?",
    coelho: "Where is the owl already sitting, while you wait for a sign from somewhere else?",
  },
  dionysus: {
    campbell: "Where has order become a kind of death, and what would a true undoing look like?",
    franz: "Which mask is still a tool, and which has grown onto the face?",
    hillman: "What sacred undoing is asking to be lived, not binged and then regretted?",
    coelho: "What marvel are you missing because you will not put the mask down for an hour?",
  },
  odin: {
    campbell: "Which eye are you being asked to give up: comfort, certainty, reputation?",
    franz: "What knowledge have you already paid for and still refuse to use?",
    hillman: "If the ending is not yours to prevent, what image is still yours to serve?",
    coelho: "What would you hang on the tree of your week, not as drama, as looking?",
  },
  freyja: {
    campbell: "What would you seek if longing were allowed to be a quest, not a shame?",
    franz: "Where have you been asked to split tenderness from power?",
    hillman: "Which of your tears is gold, evidence of value, and which is a tax you no longer owe?",
    coelho: "What omen of wanting have you been treating as a character flaw?",
  },
  loki: {
    campbell: "Where are you the glitch a room needs, and where are you the glitch because you cannot belong?",
    franz: "What shape have you taken to survive that the tale no longer requires?",
    hillman: "If you stopped making trouble, what quieter image would you have to feel?",
    coelho: "What language is the world using, that you answer only with a joke?",
  },
  sigurd: {
    campbell: "Which dragon in your life was once a person, including you?",
    franz: "Whose warning have you understood and still not heeded?",
    hillman: "What gold are you guarding that costs more than it gives the soul?",
    coelho: "What bird already told you, and you called it coincidence?",
  },
  isis: {
    campbell: "Which piece of yourself have you declared lost that is only missing?",
    franz: "Where are you being asked to invent what cannot be found?",
    hillman: "What would reconstitution look like, as opposed to a replica of the old life?",
    coelho: "What small searching in your day is already the looking that mends?",
  },
  osiris: {
    campbell: "What life is over, even if you are still sitting in its chair?",
    franz: "Where could a death of role become a change of office, not a failure?",
    hillman: "What are you still trying to resurrect that wants to become compost for soul?",
    coelho: "What would you plant in the year that has already ended?",
  },
  thoth: {
    campbell: "If your heart were weighed tomorrow, what feather would it have to match?",
    franz: "Which story of yours is still only spoken, and would change if it were written?",
    hillman: "Where are you mediating other people’s wars to avoid your own page?",
    coelho: "What true word is already on the spoon, while you wait for a better script?",
  },
  maat: {
    campbell: "What are you calling complexity that is actually a refusal to come back into proportion?",
    franz: "Whose heart are you weighing besides your own?",
    hillman: "What would lightness mean in your actual week: not as mood, as image?",
    coelho: "Where is the feather already, in an ordinary fairness you keep postponing?",
  },
  anansi: {
    campbell: "What story of yours is still locked in a sky you have not bargained with?",
    franz: "Where are you small enough to win, and where are you only hiding?",
    hillman: "If the treasure is the right to tell, what are you still paying force for?",
    coelho: "What tale is the world trying to give you, if you would stop hoarding the punchline?",
  },
  sundiata: {
    campbell: "What delay have you mistaken for a verdict?",
    franz: "Who laughed early, and what would standing in front of them cost you now?",
    hillman: "If the boon is a people, not a trophy, what are you actually trying to found?",
    coelho: "What first step is already in the body, while the court is still laughing?",
  },
  makeda: {
    campbell: "Where are you still waiting to be taught by a room that should meet you as an equal?",
    franz: "Which of your tests have you swallowed to keep the table pleasant?",
    hillman: "What would you take home if the visit were allowed to change the map of soul?",
    coelho: "What riddle did you bring, and forget to ask?",
  },
  chameleon: {
    campbell: "What true word of yours is moving at chameleon speed, and who is running ahead of it?",
    franz: "Which first report have you built a whole cosmology on?",
    hillman: "If death entered as a timing error, what timing error are you still treating as a law?",
    coelho: "What message is late, and still the one you must deliver?",
  },
  amaterasu: {
    campbell: "What light in you went underground as a form of self-protection?",
    franz: "Who is dancing outside your cave without demanding that you perform?",
    hillman: "If you saw your own brilliance without flinching, what image would you have to serve?",
    coelho: "What laughter in the ordinary day is trying to coax you back?",
  },
  momotaro: {
    campbell: "What island of trouble are you still approaching as if you had to be the only one?",
    franz: "Which instinct (loyal, clever, far-seeing) have you left hungry?",
    hillman: "What ordinary provision, the dumpling, is your actual magic?",
    coelho: "Who is already walking with you, that you keep calling a coincidence?",
  },
  weaver: {
    campbell: "Where are you demanding a life with no river in it?",
    franz: "Which figure are you living, the weaver or the cowherd, and which have you exiled as a hobby?",
    hillman: "What image of fusion are you still curing, that wants to stay two?",
    coelho: "When is the next crossing, and will you keep it as an omen, not a mood?",
  },
  nuwa: {
    campbell: "Where are you waiting for an unbroken world instead of becoming the one who patches this one?",
    franz: "What would a visible mend look like in your life: honest, not hidden?",
    hillman: "Which of your creations was made by hand, and which by the cord of haste?",
    coelho: "What stone of the right color is already in the room, waiting to be smelted?",
  },
  "crane-wife": {
    campbell: "Which gift of yours is made of your own feathers?",
    franz: "Where has curiosity become a way of not trusting the tale?",
    hillman: "What room in your life needs a closed door to remain alive as soul, not as secret?",
    coelho: "What would you have to stop watching, in order to keep the cloth?",
  },
  sita: {
    campbell: "Whose reputation are you protecting at the cost of your own ground?",
    franz: "Where is endurance still sacred, and where has it become a habit of being tested?",
    hillman: "What would it mean to return to the earth that knows you, even if a kingdom wanted a performance?",
    coelho: "What proof is being demanded that love should not have to give?",
  },
  arjuna: {
    campbell: "Where are you frozen between two armies that both look like family?",
    franz: "Who is the charioteer in you, and have you let them speak?",
    hillman: "What would right action be if it were not about winning the old war?",
    coelho: "What conversation in the chariot is the omen, before you pick the bow up?",
  },
  draupadi: {
    campbell: "Where are you being treated as stakes in someone else’s game?",
    franz: "Which of your angers is actually a legal question no one in the room would answer?",
    hillman: "What would it mean to keep a vow of memory without becoming only the vow?",
    coelho: "What have you braided back too soon, as if the hall had already answered?",
  },
  hanuman: {
    campbell: "What sea would you cross if you remembered your size?",
    franz: "Where are you still living under a curse of smallness that has already expired?",
    hillman: "If your chest were opened, what name would be written there, and is it still the right one?",
    coelho: "Who is trying to remind you, and have you treated them as an omen or a nuisance?",
  },
  savitri: {
    campbell: "What fate did you marry with your eyes open, and how will you walk beside it?",
    franz: "Where have you been wailing when a precise sentence was needed?",
    hillman: "Which boon are you actually asking for, beneath the ones you think you are allowed?",
    coelho: "What would you say, calmly, to the thing that is taking what you love?",
  },
  quetzalcoatl: {
    campbell: "If you sailed east, what dawn would you actually be seeking?",
    franz: "Where has purity become the enemy of your continuing?",
    hillman: "What bones are you being asked to retrieve from the underworld of your own past?",
    coelho: "What gift went into exile because you could not bear a stain on the ordinary day?",
  },
  ixchel: {
    campbell: "Where are you trying to be a full moon on a new-moon day?",
    franz: "What is being born through you that you keep treating as an inconvenience?",
    hillman: "Which of your floods is a destruction, and which is a washing of the loom?",
    coelho: "What phase of the week is the omen, if you stop treating life as a straight line?",
  },
  brigid: {
    campbell: "What is in the forge, what is in the poem, and what is in the well, and which did you abandon?",
    franz: "Where do you need heat under control rather than more heat?",
    hillman: "What small seasonal stirring are you dismissing because it is not yet spring?",
    coelho: "What cloth would you leave out overnight, as a looking, not a superstition?",
  },
  salmon: {
    campbell: "Whose salmon were you cooking when your own life changed?",
    franz: "What small burn is trying to become a way of knowing?",
    hillman: "If you already know, what are you still pretending to be a student of?",
    coelho: "What did you taste by accident that you now have a responsibility to notice?",
  },
  blodeuwedd: {
    campbell: "Where were you made of flowers, assembled to be suitable, and what would a self-made night look like?",
    franz: "What betrayal of yours was also a first attempt at having a preference?",
    hillman: "If you are the owl now, what can you see that the garden could not?",
    coelho: "Which of your features were arranged for someone else’s story, and what omen is the night?",
  },
  cuchulainn: {
    campbell: "Which geis of yours is a sacred limit, and which is a superstition?",
    franz: "Where do you need a vat of cold water more than another victory?",
    hillman: "What would it mean to stand down without being tied to the stone?",
    coelho: "What ford are you still holding as if no one else could be trained?",
  },
  inanna: {
    campbell: "What would you have to take off to enter the next room of your life?",
    franz: "Who failed to mourn you, including you, and what does that failure ask?",
    hillman: "If you are back from below, what new authority are you refusing to exercise?",
    coelho: "Which gate are you at, and what ordinary glory are you still trying to wear through it?",
  },
  gilgamesh: {
    campbell: "Who was your Enkidu, the equal, and what did their absence send you hunting?",
    franz: "What plant of exemption are you still clutching?",
    hillman: "If you looked at the walls of your actual life, what would count as enough for soul?",
    coelho: "What immortality project is standing in for a grief you have not walked?",
  },
  raven: {
    campbell: "What are you waiting to be given that you may have to steal from a too-small room?",
    franz: "Where has your hunger been more honest than your virtue?",
    hillman: "If the sun came out tomorrow, what image would you no longer be able to hide?",
    coelho: "What light is still in a box because the owner of the box enjoys the dark?",
  },
  sedna: {
    campbell: "What betrayal are you still calling the weather?",
    franz: "Whose hair, including yours, has gone uncombed while everyone waited for food?",
    hillman: "If the creatures of your life come from a wound, how will you honor the wound without worshipping the knife?",
    coelho: "What would it mean to go down, gently, and comb, as a looking not a rescue?",
  },
  maui: {
    campbell: "Where are you still slowing the sun because you do not trust there is enough day?",
    franz: "Which exploit is service, and which is an inability to rest in a finished gift?",
    hillman: "What would enough world feel like in the body, not as a slogan?",
    coelho: "What island have you already fished up that you have not yet consented to live on?",
  },
  scheherazade: {
    campbell: "Who in your life is Shahryar, and what tale is keeping the knife down?",
    franz: "Where have you become only the storyteller, never the one who gets to sleep?",
    hillman: "What would a last night look like: not as death, as completion of an image?",
    coelho: "What story are you leaving unfinished in order to survive, and is it still time?",
  },
};
