import type { OmenMoon, Weights } from "./types";
import type { SigilKind } from "./types";

export type Omen = {
  id: string;
  title: string;
  body: string;
  prompt: string;
  sigil: SigilKind;
  moon: OmenMoon;
  weights: Weights;
};

export const OMENS: Omen[] = [
  {
    id: "unopened",
    title: "The unopened thing",
    body: "Something in the room has been treated as furniture. It is still a door.",
    prompt: "What have you been walking past that is waiting to be used as an entrance?",
    sigil: "key",
    moon: "new",
    weights: { threshold: 2, craft: 1 },
  },
  {
    id: "small-fire",
    title: "A fire the size of a thought",
    body: "Do not wait for a blaze. Feed what is already warm.",
    prompt: "What tiny heat in your life is asking to be taken seriously?",
    sigil: "flame",
    moon: "waxing",
    weights: { devotion: 2, craft: 1 },
  },
  {
    id: "too-much-light",
    title: "Too much light",
    body: "Fullness can be a kind of glare. Some truths need a softer hour.",
    prompt: "What are you over-illuminating that would heal in partial shade?",
    sigil: "moon",
    moon: "full",
    weights: { shadow: 1, sovereignty: 1, descent: 1 },
  },
  {
    id: "comb",
    title: "Hair in the current",
    body: "The source of food is tangled. Going down gently is the work, not another hunt.",
    prompt: "What grief have you left uncombed while you waited for provision?",
    sigil: "bone",
    moon: "waning",
    weights: { descent: 2, devotion: 1 },
  },
  {
    id: "thread-hand",
    title: "Thread in the hand",
    body: "You already know the maze. The question is whether you will keep being the map.",
    prompt: "Who has been using your thread, and what would you build if you kept it?",
    sigil: "thread",
    moon: "any",
    weights: { craft: 2, sovereignty: 1 },
  },
  {
    id: "two-colors",
    title: "Two messages",
    body: "A slow word and a fast word were sent. The world kept the one that arrived first.",
    prompt: "Which message in your life is only first, not true?",
    sigil: "moon",
    moon: "any",
    weights: { trickster: 2, threshold: 2 },
  },
  {
    id: "sweet-water",
    title: "Sweet water",
    body: "A system dries when delight is treated as optional. Honey is not a decoration.",
    prompt: "What sweetness did you leave out of your own making?",
    sigil: "cup",
    moon: "waxing",
    weights: { eros: 2, devotion: 1 },
  },
  {
    id: "cave-laugh",
    title: "Laughter at the cave mouth",
    body: "The light does not return because it is scolded. It returns because the world becomes interesting.",
    prompt: "What would make the mouth of your cave interesting again?",
    sigil: "star",
    moon: "new",
    weights: { return: 2, descent: 1 },
  },
  {
    id: "unfinished-tale",
    title: "The tale left ajar",
    body: "A story unfinished can keep a knife down. It can also keep you from sleep.",
    prompt: "Is the story you are telling still saving a life, including yours?",
    sigil: "thread",
    moon: "full",
    weights: { craft: 2, trickster: 1, devotion: 1 },
  },
  {
    id: "ford-alone",
    title: "Someone at the ford",
    body: "Holding a crossing alone is a gift until it becomes a refusal to train the next person.",
    prompt: "What are you still fighting as if no one else could be taught?",
    sigil: "blade",
    moon: "any",
    weights: { quest: 2, sovereignty: 1, shadow: 1 },
  },
  {
    id: "visible-mend",
    title: "A visible mend",
    body: "The sky can be patched with colored stone. Perfectionism hates the seam. Soul prefers a world you can live in.",
    prompt: "What would an honest mend look like in this week of your life?",
    sigil: "mountain",
    moon: "waning",
    weights: { craft: 3, return: 1 },
  },
  {
    id: "lamp",
    title: "Oil on the lamp",
    body: "Looking is not always love. Sometimes it is the end of a spell that needed the dark a little longer.",
    prompt: "What are you checking on too soon?",
    sigil: "moth",
    moon: "full",
    weights: { eros: 2, descent: 1 },
  },
  {
    id: "dumpling",
    title: "The ordinary provision",
    body: "The island of trouble is rarely a solo myth. Pack food. Feed the instincts. Go.",
    prompt: "Which companion (loyal, clever, far-seeing) have you left hungry?",
    sigil: "seed",
    moon: "waxing",
    weights: { quest: 1, devotion: 2 },
  },
  {
    id: "weighing",
    title: "A feather on the table",
    body: "Some heaviness is not mystery. It is a lie asking to be named, so the heart can match the air.",
    prompt: "What are you calling complexity that is actually a refusal of proportion?",
    sigil: "scale",
    moon: "any",
    weights: { sovereignty: 2, threshold: 1 },
  },
  {
    id: "east",
    title: "A departure east",
    body: "A gift went into exile because it could not bear a stain. Dawn is still a possible office.",
    prompt: "What of yours left town over a night of being merely human?",
    sigil: "serpent",
    moon: "waning",
    weights: { shadow: 2, craft: 1, return: 1 },
  },
  {
    id: "peach",
    title: "An unusual origin",
    body: "You may have arrived by a door that does not match the family story. That is allowed.",
    prompt: "What origin of yours still feels like a secret, and what if it is a provision?",
    sigil: "seed",
    moon: "new",
    weights: { threshold: 1, trickster: 1, quest: 1 },
  },
  {
    id: "owl-hour",
    title: "Night vision",
    body: "A garden identity is over. The owl can see what noon could not. Do not apologize for the hour.",
    prompt: "If you are the owl now, what becomes visible?",
    sigil: "owl",
    moon: "waning",
    weights: { shadow: 2, sovereignty: 1 },
  },
  {
    id: "bridge-night",
    title: "One appointed crossing",
    body: "Two callings can be real. Fusion would wreck both. The magpies only come when you keep the date.",
    prompt: "Where have you been demanding a life with no river in it?",
    sigil: "bridge",
    moon: "full",
    weights: { eros: 2, craft: 1, threshold: 1 },
  },
  {
    id: "stolen-sun",
    title: "Light from a box",
    body: "The motive may be hunger. The day is still day. A messy messenger can deliver a necessary noon.",
    prompt: "What light is still boxed because the owner enjoys the dark?",
    sigil: "bird",
    moon: "waxing",
    weights: { trickster: 3, return: 1 },
  },
  {
    id: "seven-gates",
    title: "A gate, a garment",
    body: "You cannot take every glory into the next chamber. Subtraction is not humiliation. It is the ticket.",
    prompt: "Which piece of splendor are you still trying to wear through a door that asks you to unhook it?",
    sigil: "aperture",
    moon: "new",
    weights: { descent: 3, sovereignty: 1 },
  },
  {
    id: "walls-of-uruk",
    title: "Look at the walls",
    body: "The plant of exemption was lost. The city remains. Enough is a kind of immortality that can be inhabited.",
    prompt: "What quest for forever is standing in for a grief you have not finished?",
    sigil: "wall",
    moon: "any",
    weights: { return: 2, quest: 1, craft: 1 },
  },
  {
    id: "cold-vat",
    title: "A vat of cold water",
    body: "Going beyond a limit is a gift. Coming back is a craft. The ford is not the only scene.",
    prompt: "Where do you need cooling more than another victory?",
    sigil: "blade",
    moon: "full",
    weights: { shadow: 2, quest: 1, sovereignty: 1 },
  },
  {
    id: "imbolc",
    title: "A stirring under winter",
    body: "Not spring. The first small heat. Dismissing it because it is not a festival is how fires go out.",
    prompt: "Which of your three fires (making, saying, healing) has gone out from neglect?",
    sigil: "flame",
    moon: "waxing",
    weights: { craft: 2, threshold: 1, devotion: 1 },
  },
  {
    id: "forgotten-size",
    title: "Remembered voltage",
    body: "A curse of smallness can expire without announcing itself. Someone may already be reminding you.",
    prompt: "What strength did you forget, and who is trying to tell you?",
    sigil: "mountain",
    moon: "waxing",
    weights: { devotion: 2, quest: 2 },
  },
];

export const OMEN_BY_ID = Object.fromEntries(OMENS.map((o) => [o.id, o]));
