/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as CarryRouteImport } from './routes/carry'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ConstellationRouteImport } from './routes/constellation'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OmenRouteImport } from './routes/omen'
import { Route as PatternRouteImport } from './routes/pattern'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryMythIdRouteImport } from './routes/library.$mythId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const CarryRoute = CarryRouteImport.update({
  id: '/carry',
  path: '/carry',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationRoute = ConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OmenRoute = OmenRouteImport.update({
  id: '/omen',
  path: '/omen',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternRoute = PatternRouteImport.update({
  id: '/pattern',
  path: '/pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryMythIdRoute = LibraryMythIdRouteImport.update({
  id: '/$mythId',
  path: '/$mythId',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/carry': typeof CarryRoute
  '/codex': typeof CodexRoute
  '/constellation': typeof ConstellationRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/omen': typeof OmenRoute
  '/pattern': typeof PatternRoute
  '/library/$mythId': typeof LibraryMythIdRoute
  '/library/': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/carry': typeof CarryRoute
  '/codex': typeof CodexRoute
  '/constellation': typeof ConstellationRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/omen': typeof OmenRoute
  '/pattern': typeof PatternRoute
  '/library/$mythId': typeof LibraryMythIdRoute
  '/library': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/carry': typeof CarryRoute
  '/codex': typeof CodexRoute
  '/constellation': typeof ConstellationRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/omen': typeof OmenRoute
  '/pattern': typeof PatternRoute
  '/library/$mythId': typeof LibraryMythIdRoute
  '/library/': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridge'
    | '/carry'
    | '/codex'
    | '/constellation'
    | '/journal'
    | '/library'
    | '/login'
    | '/omen'
    | '/pattern'
    | '/library/$mythId'
    | '/library/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridge'
    | '/carry'
    | '/codex'
    | '/constellation'
    | '/journal'
    | '/login'
    | '/omen'
    | '/pattern'
    | '/library/$mythId'
    | '/library'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bridge'
    | '/carry'
    | '/codex'
    | '/constellation'
    | '/journal'
    | '/library'
    | '/login'
    | '/omen'
    | '/pattern'
    | '/library/$mythId'
    | '/library/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgeRoute: typeof BridgeRoute
  CarryRoute: typeof CarryRoute
  CodexRoute: typeof CodexRoute
  ConstellationRoute: typeof ConstellationRoute
  JournalRoute: typeof JournalRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  OmenRoute: typeof OmenRoute
  PatternRoute: typeof PatternRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carry': {
      id: '/carry'
      path: '/carry'
      fullPath: '/carry'
      preLoaderRoute: typeof CarryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellation': {
      id: '/constellation'
      path: '/constellation'
      fullPath: '/constellation'
      preLoaderRoute: typeof ConstellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omen': {
      id: '/omen'
      path: '/omen'
      fullPath: '/omen'
      preLoaderRoute: typeof OmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern': {
      id: '/pattern'
      path: '/pattern'
      fullPath: '/pattern'
      preLoaderRoute: typeof PatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$mythId': {
      id: '/library/$mythId'
      path: '/$mythId'
      fullPath: '/library/$mythId'
      preLoaderRoute: typeof LibraryMythIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryMythIdRoute: typeof LibraryMythIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryMythIdRoute: LibraryMythIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgeRoute: BridgeRoute,
  CarryRoute: CarryRoute,
  CodexRoute: CodexRoute,
  ConstellationRoute: ConstellationRoute,
  JournalRoute: JournalRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LoginRoute: LoginRoute,
  OmenRoute: OmenRoute,
  PatternRoute: PatternRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
